name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build APK
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          python-version: "3.10"
          buildozer-args: android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: APK文件
          path: bin/*.apk
